### ISSUE TITLE
Bug: duckduckgo engine

### ISSUE THREAD

**Issue by tnnzy** [tiekoetter/searxng#33] opened 2022-11-03 07:53 UTC
**Version of SearXNG, commit number if you are using on master branch and stipulate if you forked SearXNG**
Repository: https://github.com/tiekoetter/searxng
Branch: master
Version: 2022.10.29-fc9986de (983c85f7)

**How did you install SearXNG?**

**What happened?**

**How To Reproduce**

**Expected behavior**

**Screenshots & Logs**

**Additional context**

**Technical report**

Error
  * Error: searx.exceptions.SearxEngineAccessDeniedException
  * Percentage: 10
  * Parameters: `('HTTP error 403',)`
  * File name: `searx/search/processors/online.py:113`
  * Function: `_send_http_request`
  * Code: `response = req(params['url'], **request_args)`

**Comment by tiekoetter** [comment] 2022-11-05 11:37
Duplicate of #15

**Closed by tiekoetter** 2022-11-05 11:37 UTC
Labels: bug
