### ISSUE TITLE
Bug: google engine

### ISSUE THREAD

**Issue by eightyy8** [tiekoetter/searxng#32] opened 2022-10-21 19:57 UTC
**Version of SearXNG, commit number if you are using on master branch and stipulate if you forked SearXNG**
Repository: https://github.com/tiekoetter/searxng
Branch: master
Version: 2022.10.21-710a3a00 (7d19e4a4)

**How did you install SearXNG?**

**What happened?**

**How To Reproduce**

**Expected behavior**

**Screenshots & Logs**

**Additional context**

**Technical report**

Error
  * Error: searx.exceptions.SearxEngineAccessDeniedException
  * Percentage: 0
  * Parameters: `('HTTP error 403',)`
  * File name: `searx/search/processors/online.py:113`
  * Function: `_send_http_request`
  * Code: `response = req(params['url'], **request_args)`

Error
  * Error: httpx.TimeoutException
  * Percentage: 0
  * Parameters: `(None, None, None)`
  * File name: `searx/search/processors/online.py:113`
  * Function: `_send_http_request`
  * Code: `response = req(params['url'], **request_args)`

**Comment by tiekoetter** [comment] 2022-10-21 20:32
Should be fixed now. I am unsure of the cause. So this will issue will remain open.

**Comment by eightyy8** [comment] 2022-10-24 12:18
> Should be fixed now. I am unsure of the cause. So this will issue will remain open.

Stopped working, getting same consistent error:

```
**Version of SearXNG, commit number if you are using on master branch and stipulate if you forked SearXNG**
Repository: https://github.com/tiekoetter/searxng
Branch: master
Version: 2022.10.21-710a3a00 (7d19e4a4)
<!-- Check if these values are correct -->

**How did you install SearXNG?**
<!-- Did you install SearXNG using the official wiki or using searxng-docker
or manually by executing the searx/webapp.py file? -->
**What happened?**
<!-- A clear and concise description of what the bug is. -->

**How To Reproduce**
<!-- How can we reproduce this issue? (as minimally and as precisely as possible) -->

**Expected behavior**
<!-- A clear and concise description of what you expected to happen. -->

**Screenshots & Logs**
<!-- If applicable, add screenshots, logs to help explain your problem. -->

**Additional context**
<!-- Add any other context about the problem here. -->

**Technical report**

Error
  * Error: httpx.TimeoutException
  * Percentage: 0
  * Parameters: `(None, None, None)`
  * File name: `searx/search/processors/online.py:113`
  * Function: `_send_http_request`
  * Code: `response = req(params['url'], **request_args)`

Error
  * Error: searx.exceptions.SearxEngineAccessDeniedException
  * Percentage: 0
  * Parameters: `('HTTP error 403',)`
  * File name: `searx/search/processors/online.py:113`
  * Function: `_send_http_request`
  * Code: `response = req(params['url'], **request_args)`


```

**Comment by aaronliu0130** [comment] 2022-10-28 01:24
Got this access denied exception again today.

**Closed** 2022-10-31 08:51 UTC
Labels: bug, investigating

**Comment by aaronliu0130** [comment] 2022-10-31 22:36
Issue still here

**Comment by Gerome100** [comment] 2022-11-02 13:21
same here

**Comment by Pagal3** [comment] 2022-11-05 18:24
Issue still present

**Comment by eightyy8** [comment] 2022-11-05 18:40
Use https://searx.be until then.
