### ISSUE TITLE
Bug: invidious engine

### ISSUE THREAD

**Issue by Mennaruuk** [tiekoetter/searxng#6] opened 2022-03-11 16:46 UTC
**Version of SearXNG, commit number if you are using on master branch and stipulate if you forked SearXNG**
Repository: https://github.com/tiekoetter/searxng
Branch: master
Version: 2022.03.11-9941a826 (c0f7e0a4)

**How did you install SearXNG?**

**What happened?**

**How To Reproduce**

**Expected behavior**

**Screenshots & Logs**

**Additional context**

**Technical report**

Error
  * Error: 2 redirects, maximum: 0
  * Percentage: 30
  * Parameters: `('200', 'OK', 'invidious.snopyta.org')`
  * File name: `searx/search/processors/online.py:105`
  * Function: `_send_http_request`
  * Code: `count_error(`

Error
  * Error: json.decoder.JSONDecodeError
  * Percentage: 30
  * Parameters: `('Expecting value',)`
  * File name: `searx/engines/invidious.py:60`
  * Function: `response`
  * Code: `search_results = resp.json()`

Error
  * Error: httpx.ReadTimeout
  * Percentage: 15
  * Parameters: `(None, None, 'invidio.xamh.de')`
  * File name: `searx/search/processors/online.py:96`
  * Function: `_send_http_request`
  * Code: `response = req(params['url'], **request_args)`

**Comment by tiekoetter** [comment] 2022-03-11 22:52
Thank you for reporting.

I can confirm that I also have encountered these issues with invidious before. I will investigate it and report back.

**Comment by tiekoetter** [comment] 2022-03-21 07:26
The issue is is now fixed.

**Closed by tiekoetter** 2022-03-21 07:26 UTC
Labels: bug

**Comment by tiekoetter** [comment] 2022-04-04 21:34
**Update:** Switched to a self-hosted Invidious instance because all other instances would block my SearXNG instance.
